logging:
  version: 1
  formatters:
    verbose:
      format: '%(asctime)s;%(name)-24s;%(levelname)-8s;%(message)s'
    simple:
      format: '%(name)-24s: %(levelname)-8s %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
    filelog:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: verbose
      filename: camacq.log
      maxBytes: 1048576
      backupCount: 9
      encoding: utf-8
      delay: 0
  loggers:
    root:
      level: DEBUG
      handlers: [console, file]
other:
